%% Import data from text file
% Script for importing data from the following text file:
%
% filename: cpu_performance.txt
%
% Auto-generated by MATLAB on 26-Aug-2022 16:30:10

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 10);

% Specify range and delimiter
opts.DataLines = [9, Inf];
opts.Delimiter = ";";

% Specify column names and types
opts.VariableNames = ["XSize", "YSize", "ZSize", "MATLAB", "Laptop", "Desktop", "Server1", "Server2", "Server3", "Memory"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
tbl = readtable("cpu_performance.txt", opts);

%% Convert to output type
XSize = tbl.XSize;
YSize = tbl.YSize;
ZSize = tbl.ZSize;
MATLAB = tbl.MATLAB;
Laptop = tbl.Laptop;
Desktop = tbl.Desktop;
Server1 = tbl.Server1;
Server2 = tbl.Server2;
Server3 = tbl.Server3;
Memory = tbl.Memory;

loglog(XSize.*YSize.*ZSize,MATLAB)
hold on
loglog(XSize.*YSize.*ZSize,Laptop)
loglog(XSize.*YSize.*ZSize,Desktop)
loglog(XSize.*YSize.*ZSize,Server1)
loglog(XSize.*YSize.*ZSize,Server2)
loglog(XSize.*YSize.*ZSize,Server3)
grid on
legend('MATLAB','Laptop','Desktop','Server 1','Server 2', 'Server 3')
xlabel('Total Number of Grid Points')
ylabel('Compute Time Per Timestep [ms]')


%% Clear temporary variables
clear opts tbl


%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 10);

% Specify range and delimiter
opts.DataLines = [7, Inf];
opts.Delimiter = ";";

% Specify column names and types
opts.VariableNames = ["XSize", "YSize", "ZSize", "MATLAB", "GTX580", "GTX680", "K20m", "GTX980", "TITANX", "Memory"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
tbl = readtable("gpu_performance.txt", opts);

%% Convert to output type
XSize = tbl.XSize;
YSize = tbl.YSize;
ZSize = tbl.ZSize;
MATLAB = tbl.MATLAB;
GTX580 = tbl.GTX580;
GTX680 = tbl.GTX680;
K20m = tbl.K20m;
GTX980 = tbl.GTX980;
TITANX = tbl.TITANX;
Memory = tbl.Memory;

%% Clear temporary variables
clear opts tbl

GridSize = XSize.*YSize.*ZSize;

figure
loglog(GridSize,MATLAB)
hold on
loglog(GridSize,GTX580)
loglog(GridSize,GTX680)
loglog(GridSize,K20m)
loglog(GridSize,GTX980)
loglog(GridSize,TITANX)
grid on
legend('MATLAB', 'GTX580', 'GTX680', 'K20m', 'GTX980', 'TITANX')
xlabel('Total Number of Grid Points')
ylabel('Compute Time Per Timestep [ms]')


%%

maxfac = zeros(size(GridSize));

for i = 1:length(GridSize)
    
    maxfac(i) = max(factor(GridSize(i)));
    
end

figure
semilogx(GridSize,maxfac)

GridSize2  = GridSize((maxfac==2));
GridSize3  = GridSize((maxfac==3));
GridSize5  = GridSize((maxfac==5));
GridSize7  = GridSize((maxfac==7));
GridSize11 = GridSize((maxfac==11));
GridSize13 = GridSize((maxfac==13));

y = MATLAB;

y2  = y((maxfac==2));
y3  = y((maxfac==3));
y5  = y((maxfac==5));
y7  = y((maxfac==7));
y11 = y((maxfac==11));
y13 = y((maxfac==13));

x = [0 512^3];

p = polyfit(GridSize2,y2,1);
yfit2 = p(1)*x+p(2);

p = polyfit(GridSize3,y3,1);
yfit3 = p(1)*x+p(2);

p = polyfit(GridSize5,y5,1);
yfit5 = p(1)*x+p(2);

p = polyfit(GridSize7,y7,1);
yfit7 = p(1)*x+p(2);

p = polyfit(GridSize11,y11,1);
yfit11 = p(1)*x+p(2);

p = polyfit(GridSize13,y13,1);
yfit13 = p(1)*x+p(2);



figure
plot(x, yfit2)
hold on
plot(x, yfit3)
plot(x, yfit5)
plot(x, yfit7)
plot(x, yfit11)
plot(x, yfit13)

grid on
xlabel('Total Number of Grid Points')
ylabel('Compute Time Per Timestep [ms]')